### PR TITLE
Set up inotifywait *before* checking things exist

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Review by Saviq — APPROVED** [review]
Yup.

**Comment by AlanGriffiths** [comment]
> Would have been nice with a warning during build or a fallback to the good old sleep 4.

I'm not sure how it would be possible to get a warning during build when the recipe isn't part of `mir-kiosk-snap-launch`. We could add a check to the README, but that already has:

```yaml
    stage-packages:
      - inotify-tools
```

As you observe, the current version should fail even the most cursory test. But if you have a better approach, PRs welcome.

**Comment by perceptoid** [comment]
Not sure what the best solution is (somewhat out of my usually area), but I thought I would leave the information for others struggling with a sudden black-out of mir-kiosk based systems after a potentially minor mir/display-unrelated update. New systems are probably fine given the README and examples, but existing systems chugging along without inotifywait might suddenly stumble for no (initially) appararent reason.

**Comment by wmww** [comment]
If this is likely to happen again, could we detect that inotifywait does not exist and do some fallback behavior (along with a warning, of course)?

**Pull request merged**
