### PR TITLE
Better setup.sh script

### PR DESCRIPTION
**Pull request by AlanGriffiths**
1. Detect already connected interfaces
2. Find available providers for content interfaces

### CODE REVIEW

**Review by Saviq — CHANGES_REQUESTED** [review]
Doesn't seem to work:

```plain
$ /snap/mir-kiosk-scummvm/current/bin/setup.sh
error: no such interface
Warning: Failed to connect 'graphics-core20'. Please connect manually, available providers are:

$ snap interface content
name:    content
summary: allows sharing code and data with other snaps
plugs:
  - juju:peers
  - mir-kiosk-kodi:graphics-core20
  - mir-kiosk-scummvm:graphics-core20
  - ubuntu-frame:graphics-core20
slots:
  - docker:docker-executables
  - gtk-common-themes:gtk-2-themes
  - gtk-common-themes:gtk-3-themes
  - gtk-common-themes:icon-themes
  - gtk-common-themes:sound-themes
  - mesa-core20:graphics-core20

**Review by Saviq — APPROVED** [review]
OK I suppose it can't be worse than it is :P

bors merge

**Comment by AlanGriffiths** [comment]
@Saviq there's no automation here. Sorry.

**Comment by Saviq** [comment]
D'oh.

**Pull request merged**
